---
- name: Run Linux selftest {{ selftests_script }}
  become: yes
  become_method: sudo
  command: "{{ selftests_script }}"
  register: self_out
  changed_when: "self_out.rc == 0"
  args:
    chdir: "{{ selftests_linux_dir }}"
    executable: /bin/bash
  tags: [ 'selftest_script' ]

- debug: msg="{{ self_out.stdout_lines }}"

- debug: msg="{{ self_out.stderr_lines }}"
